### PR TITLE
projectured: update source.txt to use tagged-git instead of branched-git

### PR DESCRIPTION
**Pull request by attila-lendvai**

### CODE REVIEW

**Comment by quicklisp** [comment]
Why?

**Comment by attila-lendvai** [comment]
to push:

```
$ git push -f origin taggg
Counting objects: 1, done.
Writing objects: 100% (1/1), 163 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To /tmp/origin
 + f54c750...7e88e2e taggg -> taggg (forced update)
```

to pull:

```
$ git tag -ln
taggg           tag test banan
$ git pull --tags
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (1/1), done.
From /tmp/origin
 - [tag update]      taggg      -> taggg
Already up-to-date.
$ git tag -ln
taggg           asdfffff tag desc
```

**Comment by attila-lendvai** [comment]
note: ```fetch --tags``` also works the same as ```pull```. i've created a PR for the ql-controller repo to add it.

**Comment by fiddlerwoaroof** [comment]
Maybe it'd be better to expect a tag of the format `quicklisp-<id>` where the lexically greatest <id> is pulled as the current version?  That way, you don't have to move tags around and can keep track of all the released commits.

**Comment by attila-lendvai** [comment]
that'd be unnecessary complexity, i think.

tags in version control systems are labels to denote a specific revision. and that's exactly what we need here: a symbolic constant that quicklisp can refer to, and that the project authors can move around freely to whichever revision they deem appropriate for the next quicklisp release.

and if git tags happen to give some headaches, then they need to be addressed/kludged (i don't think that is the case).

**Comment by attila-lendvai** [comment]
FTR, this is that PR in ql-controller: https://github.com/quicklisp/quicklisp-controller/pull/11

**Comment by ryukinix** [comment]
I think using git tag based releases is a good thing.

**Pull request closed without merging**
