### PR TITLE
Update Michael Fiano's projects to their new GitHub locations.

### PR DESCRIPTION
**Pull request by sbenitezb**
Upon discussing with Michael over email, his git server died and all his projects are now hosted on GitHub.

### CODE REVIEW

**Comment by mfiano** [comment]
@xach This is true. I haven't had time to make the PR myself yet. I give up on self hosting. My 1U fried a month after I purposed it for git hosting, and attempts to migrate it require more time than I can afford.

**Review by mfiano — CHANGES_REQUESTED** [review]
I'm fairly certain it isn't just a simple text replacement. Some repositories probably were renamed or retired. I will make a proper PR when I can find some time. Please ping me if it's urgent.

**Comment by sbenitezb** [comment]
> I'm fairly certain it isn't just a simple text replacement. Some repositories probably were renamed or retired. I will make a proper PR when I can find some time. Please ping me if it's urgent.

I did take the URLs from your github project list, they are all correct. I might have missed some project, there are a couple tools that are not on quicklisp though.

**Comment by mfiano** [comment]
Great thank you. It looks like it was merged anyway 🤔

**Pull request merged**
