### PR TITLE
Issues template

### PR DESCRIPTION
**Pull request by guicho271828**
Using new github features! https://github.com/blog/2111-issue-and-pull-request-templates
This will motivate the library authors to double-check their submissions.

### CODE REVIEW

**Comment by quicklisp** [comment]
Is the PULL_REQUIEST_TEMPLATE.md name a typo?

**Comment by guicho271828** [comment]
oh yes! thanks for pointing it out

**Comment by guicho271828** [comment]
The submission guideline may sound too restrictive, I just guessed it from your past articles. Please amend it so that it fits your taste.
Example issue : https://github.com/guicho271828/quicklisp-projects/issues/1

**Comment by fstamour** [comment]
I'm all for the pull request template, but maybe we should start with a smaller one. One that's less likely to scare new contributor? We can always leave a link to CONTRIBUTING.md or something alike. What do you think?

**Pull request closed without merging**
